### ISSUE TITLE
Add environment file

### ISSUE THREAD

**Issue by dnschouten** [KimiaLabMayo/HistopathologyFeatureExtractors#3]
Thanks for your work! Would you be able to add any environment information (requirements.txt, conda env or even a Dockerfile)? I've tried installing the major packages but am running into a lot of dependency issues.

**Comment by saghiralfasly** [comment]
Hi @dnschouten, thank you for pointing this out. please find the environment.yml file https://github.com/KimiaLabMayo/HistopathologyFeatureExtractors/blob/main/environment.yml

**Comment by dnschouten** [comment]
Thanks for the quick add! Unfortunately I'm still running into some problems with this environment. I get multiple errors, among others the inability to install openslide (attached). Could you have a look to see if you can reproduce this? 

```
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for openslide-python
  error: subprocess-exited-with-error

  × Running setup.py install for openslide-python did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running install
      /opt/conda/envs/torch/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/openslide
      copying openslide/deepzoom.py -> build/lib.linux-x86_64-3.9/openslide
      copying openslide/__init__.py -> build/lib.linux-x86_64-3.9/openslide
      copying openslide/_version.py -> build/lib.linux-x86_64-3.9/openslide
      copying openslide/lowlevel.py -> build/lib.linux-x86_64-3.9/openslide
      running build_ext
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/openslide
      gcc -pthread -B /opt/conda/envs/torch/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /opt/conda/envs/torch/include -I/opt/conda/envs/torch/include -fPIC -O2 -isystem /opt/conda/envs/torch/include -fPIC -I/opt/conda/envs/torch/include/python3.9 -c openslide/_convert.c -o build/temp.linux-x86_64-3.9/openslide/_convert.o
      error: command 'gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> openslide-python

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.


CondaEnvException: Pip failed
```

**Comment by saghiralfasly** [comment]
@dnschouten you can install openslide-python manually. BTW, this env.yml list is the entire evn i am using. You don't need to install them all. You can check and install the only package you need.

**Comment by dnschouten** [comment]
If I have to install packages manually that would defeat the purpose of having a nicely configured environment file and will surely lead to more dependency issues. Would you perhaps be able to create a distilled version of this environment which only contains the packages required for this repo? I'm sure that would greatly benefit anyone who would like to try out your work

**Comment by saghiralfasly** [comment]
@dnschouten openslide requires some steps to be done manually depending on what operating system you are using. Please follow the instructions to download it based on your OS. Anyway, in this repo, I organized the code to use patches rather than WSI. So, you don't even need the OpenSlide here. you can simply remove it from the env.yml.

**Comment by alabgh01** [comment]
@dnschouten, 
Here is the openslide [documentation page](https://openslide.org/api/python/), where you will find instructions to set it up based on you operating system, unless you create a pip environment through which you can run `pip install openslide-python` to [install ](https://pypi.org/project/openslide-python/)it. 

Let us know if you have any other questions. I will close this issue now and mark it as complete.
