### ISSUE TITLE
No publicly available pretrained weights for PathDino

### ISSUE THREAD

**Issue by johnurbanik** [KimiaLabMayo/HistopathologyFeatureExtractors#4]
The path to PathDino is a local path.

https://github.com/KimiaLabMayo/HistopathologyFeatureExtractors/blob/e2f6b24f92d71007867048b8c63591919aac08ca/Histo_feature_extractors.py#L363-L371

Uploading the weights to huggingface or some other location would be helpful.

**Comment by saghiralfasly** [comment]
Hi @johnurbanik Please fine the simple way and the pretrained PathDino feature extractor here: https://github.com/KimiaLabMayo/PathDino#pathdino-inference-on-histopathology-image
